{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "demo-app.labels" (dict "component" "frontend" "global" .Values.global) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" (dict "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-app.labels" (dict "component" "frontend" "global" .Values.global) | nindent 8 }}
    spec:
      securityContext:
        {{- include "demo-app.podSecurityContext" . | nindent 8 }}
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          command:
            {{- toYaml .Values.frontend.command | nindent 12 }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.frontend.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.frontend.securityContext.readOnlyRootFilesystem }}
{{- end }}
